# Generated by Django 2.2.16 on 2021-09-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210903_1419'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_booking'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table='app_version',
        ),
    ]
