# Generated by Django 2.2.16 on 2021-09-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20210904_1041'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_booking',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_following'),
        ),
    ]
